version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn -B clean test

workflows:
  build:
    jobs:
      - build-and-test
